Repository mlr-org/mlr, pull requests merged in 2018-06, with the labels that each got.

#2285 Travis: Fix deploy path for PDF tutorial
  tic.R
Labels: pr-ready for merge (?)

#2281 Add getResamplingIndices()
  DESCRIPTION
  R/FeatSelResult.R
  R/OptResult.R
  R/TuneMultiCritResult.R
  R/TuneResult.R
  R/getNestedTuneResults.R
  R/getResamplingIndices.R
  R/selectFeaturesExhaustive.R
  R/selectFeaturesGA.R
  R/selectFeaturesRandom.R
  R/selectFeaturesSequential.R
  R/tuneCMAES.R
  R/tuneDesign.R
  R/tuneGenSA.R
  R/tuneGrid.R
  R/tuneIrace.R
  R/tuneMBO.R
  R/tuneMultiCritGrid.R
  R/tuneMultiCritNSGA2.R
  R/tuneMultiCritRandom.R
  R/tuneRandom.R
  tests/testthat/test_base_resample_getResamplingIndices.R
  vignettes/tutorial/devel/nested_resampling.Rmd
  vignettes/tutorial/devel/resample.Rmd
Labels: pr-please review, prio-low, type-enhancement

#2292 build namespace before html tutorial deployment
  tic.R
Labels: pr-ready for merge (?)

#2297 Consistent coloring for benchmark tutorial
  vignettes/tutorial/devel/benchmark_experiments.Rmd
Labels: pr-ready for merge (?), project - tutorial

#2329 Optimize navbar logo rendering
  pkgdown/extra.css
  pkgdown/templates/navbar.html
Labels: pr-ready for merge (?), project - tutorial

#2295 Re-add missing dependencies
  DESCRIPTION
  NAMESPACE
  R/tuneCMAES.R
  R/tuneGenSA.R
  tests/testthat/test_tune_tuneMBO.R
  tic.R
  todo-files/RLearner_classif_blackboost.R
  todo-files/RLearner_regr_blackboost.R
  todo-files/test_classif_blackboost.R
  todo-files/test_regr_blackboost.R
Labels: prio-blocking

#2334 update tutorial instructions
  README.md
Labels: pr-ready for merge (?), project - tutorial

#2336 Update mlr.Rproj, update man/
  man/getResamplingIndices.Rd
  mlr.Rproj
Labels: pr-please review, type-documentation, type-enhancement

#2338 Some tutorial fixes
  .travis.yml
  pkgdown/extra.css
Labels: pr-ready for merge (?), project - tutorial

#2339 Tutorial: Add use case: regression
  _pkgdown.yml
  vignettes/tutorial/devel/usecase_regression.Rmd
Labels: pr-please review, project - tutorial

#2344 Tutorial fixes
  .gitignore
  .travis.yml
  tic.R
Labels: pr-ready for merge (?), project - tutorial
