Repository mlr-org/mlr, pull requests merged in 2018-03, with the labels that each got.

#1525 add shape parameter for PlotBMRSummary
  R/plotBMRSummary.R
Labels: pr-please review, pr-ready for merge (?)

#2129 Add names for the arguments in the makeCostMeasure function
  R/Measure_make_cost.R
Labels: pr-ready for merge (?), prio-low, type-enhancement

#2154 Rewrite measure bac to allow multiclass
  R/measures.R
  tests/testthat/test_base_measures.R
Labels: pr-ready for merge (?)

#2210 put batchmark unit test other testing group so it does not run on winbuilder
  tests/run-base.R
  tests/run-basenocran.R
  tests/testthat/test_basenocran_batchmark.R
Labels: prio-blocking

#2213 Add script to create ASCII NEWS file via Travis
  .travis.yml
  inst/convert_to_ascii_news.sh
Labels: pr-please review

#2225 pkgdown tweaks
  NEWS.md
  man/figures/logo.png
Labels: pr-ready for merge (?)

#2228 more pkgdown tweaks
  .travis.yml
  README.md
Labels: pr-ready for merge (?)

#2234 Various Travis changes, integration of pkgdown theme
  .travis.yml
  README.md
  _pkgdown.yml
  pkgdown/assets/jquery.sticky-kit.min.js
  pkgdown/assets/link.svg
  pkgdown/assets/pkgdown.css
  pkgdown/assets/pkgdown.js
  pkgdown/templates/content-authors.html
  pkgdown/templates/content-citation-authors.html
  pkgdown/templates/content-home.html
  pkgdown/templates/content-news-index.html
  pkgdown/templates/content-news.html
  pkgdown/templates/content-reference-index.html
  pkgdown/templates/content-reference-topic.html
  pkgdown/templates/content-search.html
  pkgdown/templates/content-title-body.html
  pkgdown/templates/content-vignette-index.html
  pkgdown/templates/content-vignette.html
  pkgdown/templates/footer.html
  pkgdown/templates/head.html
  pkgdown/templates/header.html
  pkgdown/templates/layout.html
  pkgdown/templates/navbar.html
  tic.R
  vignettes/tutorial/devel/pdf/mlr-tutorial.pdf
Labels: pr-please review, type-documentation

#2235 Get pkgdown search working
  pkgdown/templates/docsearch.html
  pkgdown/templates/head.html
  pkgdown/templates/layout.html
  pkgdown/templates/navbar.html
  vignettes/tutorial/devel/pdf/mlr-tutorial.pdf
Labels: pr-ready for merge (?), type-documentation
