Repository mlr-org/mlr, pull requests merged in 2018-07, with the labels that each got.

#2348 Add quote() requirement for requires()
  vignettes/tutorial/devel/create_learner.Rmd
Labels: pr-ready for merge (?), project - tutorial

#2349 Mention threshold tuning in Imbalanced classification problems
  vignettes/tutorial/devel/over_and_undersampling.Rmd
Labels: pr-please review, project - tutorial

#2360 move elmNN learner to extra learner repo
  DESCRIPTION
  R/RLearner_regr_elmNN.R
Labels: pr-ready for merge (?), project - Learners

#2354 link OpenML under "mlr-org packages"
  _pkgdown.yml
Labels: pr-ready for merge (?), project - tutorial

#2364 Tut: Re-fix #2318
  _pkgdown.yml
Labels: pr-ready for merge (?), project - tutorial

#2365 Travis: Use "old" git approach to update docs
  .travis.yml
Labels: pr-ready for merge (?), project - tutorial

#2368 Travis: Fix travis deployment of docs
  .travis.yml
Labels: project - tutorial

#2380 Travis: Hotfix false positives in check stage
  .travis.yml
  tic.R
Labels: prio-blocking, project - tutorial

#2382 Tut: "Functional Data" reviewed
  vignettes/functional_data.Rmd
Labels: pr-please review, project - tutorial

#2385 Tut: Fix build and always build tutorial
  .travis.yml
  tic.R
  vignettes/handling_of_spatial_data.Rmd
Labels: pr-ready for merge (?), project - tutorial

#2393 Tut: Enable `collapse = TRUE`
  vignettes/advanced_tune.Rmd
  vignettes/bagging.Rmd
  vignettes/benchmark_experiments.Rmd
  vignettes/classifier_calibration.Rmd
  vignettes/configureMlr.Rmd
  vignettes/cost_sensitive_classif.Rmd
  vignettes/create_filter.Rmd
  vignettes/create_imputation.Rmd
  vignettes/create_learner.Rmd
  vignettes/create_measure.Rmd
  vignettes/example_tasks.Rmd
  vignettes/feature_selection.Rmd
  vignettes/filter_methods.Rmd
  vignettes/functional_data.Rmd
  vignettes/handling_of_spatial_data.Rmd
  vignettes/hyperpar_tuning_effects.Rmd
  vignettes/impute.Rmd
  vignettes/integrated_learners.Rmd
  vignettes/learner.Rmd
  vignettes/learning_curve.Rmd
  vignettes/measures.Rmd
  vignettes/multilabel.Rmd
  vignettes/nested_resampling.Rmd
  vignettes/out_of_bag_predictions.Rmd
  vignettes/over_and_undersampling.Rmd
  vignettes/parallelization.Rmd
  vignettes/partial_dependence.Rmd
  vignettes/performance.Rmd
  vignettes/predict.Rmd
  vignettes/preproc.Rmd
  vignettes/resample.Rmd
  vignettes/roc_analysis.Rmd
  vignettes/task.Rmd
  vignettes/train.Rmd
  vignettes/tune.Rmd
  vignettes/usecase_regression.Rmd
  vignettes/visualization.Rmd
  vignettes/wrapper.Rmd
Labels: pr-please review, project - tutorial

#2396 CI: Add CI for Windows (appveyor)
  .Rbuildignore
  appveyor.yml
Labels: pr-please review

#2402 Tut: links fixed
  vignettes/example_tasks.Rmd
  vignettes/measures.Rmd
Labels: project - tutorial
