Repository mlr-org/mlr, pull requests merged in 2018-11, with the labels that each got.

#2140 Featsel using mutual information with package praznik and FSelectorRcpp
  .travis.yml
  DESCRIPTION
  NEWS.md
  R/Filter.R
  docs/articles/tutorial/feature_selection.html
  docs/articles/tutorial/feature_selection_files/figure-html/unnamed-chunk-14-1.png
  man/makeFilter.Rd
  tests/testthat/test_base_getFeatureImportance.R
  tests/testthat/test_base_getOOBPreds.R
  tests/testthat/test_featsel_FilterWrapper.R
  tests/testthat/test_featsel_fselectorrcpp.R
  tests/testthat/test_featsel_praznik.R
  vignettes/tutorial/feature_selection.Rmd
Labels: pr-please review, prio-medium, project - base, type-enhancement

#2467 Remove _R_CHECK_FORCE_SUGGESTS_ from Travis
  .travis.yml
  appveyor.yml
  tic.R
Labels: pr-ready for merge (?), prio-blocking

#2469 fix binaryToFeatures (Part of #2468)
  R/selectFeatures.R
  R/utils_opt.R
  man/makeFeatSelWrapper.Rd
  man/selectFeatures.Rd
  tests/testthat/test_base_selectFeatures.R
Labels: effort-simplefix, prio-high, type-bug

#2478 Travis: roxygen2 fix
  tic.R
Labels: pr-ready for merge (?), prio-blocking

#2474 Re-add FSelector filters
  NEWS.md
  R/Filter.R
  tests/testthat/test_base_getFeatureImportance.R
  tests/testthat/test_base_getOOBPreds.R
  tests/testthat/test_featsel_FilterWrapper.R
  tests/testthat/test_featsel_fselectorrcpp.R
  tests/testthat/test_featsel_praznik.R
  vignettes/tutorial/feature_selection.Rmd
  vignettes/tutorial/nested_resampling.Rmd
Labels: pr-ready for merge (?), project - base

#2488 pkgdown: account for non-deterministic deploy leftovers
  vignettes/tutorial/cost_sensitive_classif.Rmd
  vignettes/tutorial/learning_curve.Rmd
Labels: pr-ready for merge (?), project - tutorial

#2491 Replace purrr functions with base/BBmisc
  DESCRIPTION
  R/createSpatialResamplingPlots.R
  R/getResamplingIndices.R
  R/utils.R
Labels: project - base
