Repository mlr-org/mlr, pull requests merged in 2019-06, with the labels that each got.

#2594 Bugfix: Remove unwanted columns from filter methods table
  docs/articles/tutorial/filter_methods.html
  vignettes/tutorial/filter_methods.Rmd
Labels: pr-ready for merge (?), prio-high, type-bug, type-documentation

#2591 Tests: Various Learner fixes
  R/RLearner_classif_cforest.R
  R/RLearner_regr_cforest.R
  R/RLearner_regr_crs.R
  tests/testthat/helper_learners_all.R
Labels: pr-work in progress - not done, project - Testing

#1740 e1071::svm(): Use formula interface only if factors are present
  NEWS.md
  R/RLearner_classif_svm.R
  R/RLearner_regr_svm.R
  docs/news/index.html
  tests/testthat/test_classif_svm.R
  tests/testthat/test_regr_svm.R
Labels: pr-ready for merge (?), project - Learners

#2608 Fix h2o.glm learner
  R/RLearner_classif_h2oglm.R
  docs/articles/tutorial/feature_selection.html
  tests/testthat/test_classif_h2oglm.R
Labels: pr-ready for merge (?), prio-high

#2606 Update documentation of `par.vals`
  R/getHyperPars.R
  R/makeLearner.R
  R/setHyperPars.R
  docs/articles/tutorial/learner.html
  docs/articles/tutorial/tune.html
  docs/reference/getHyperPars.html
  docs/reference/getLearnerParVals.html
  docs/reference/makeLearner.html
  docs/reference/makeLearners.html
  docs/reference/setHyperPars.html
  man/getHyperPars.Rd
  man/getLearnerParVals.Rd
  man/makeLearner.Rd
  man/makeLearners.Rd
  man/setHyperPars.Rd
  vignettes/tutorial/learner.Rmd
  vignettes/tutorial/tune.Rmd
Labels: project - base, type-documentation

#2603 enabled quantile regression in gbm
  NEWS.md
  R/RLearner_regr_gbm.R
  tests/testthat/test_regr_gbm.R
Labels: pr-please review, project - Learners, reply-needed, type-enhancement
