Repository mlr-org/mlr, pull requests merged in 2019-05, with the labels that each got.

#1784 Update variance estimation methods for RF learners
  NEWS.md
  R/RLearner_regr_randomForest.R
  R/RLearner_regr_ranger.R
  docs/articles/tutorial/integrated_learners.html
  docs/news/index.html
  tests/testthat/test_regr_ranger.R
Labels: pr-ready for merge (?), prio-high, type-enhancement

#1653 Feature: Support facet nested cv for visualizing hyperparam effects
  NEWS.md
  R/generateHyperParsEffect.R
  docs/news/index.html
  docs/reference/plotHyperParsEffect.html
  man/plotHyperParsEffect.Rd
  tests/testthat/test_base_generateHyperParsEffect.R
Labels: pr-ready for merge (?)

#2378 tests: update learner checks with only one feature
  docs/ISSUE_TEMPLATE.html
  docs/articles/tutorial/create_learner.html
  tests/testthat/test_learners_all_classif.R
  tests/testthat/test_learners_all_regr.R
Labels: prio-high, project - base
